name: Deploy

on:
  pull_request:
    branches:
      - main

jobs:
  url_change:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Replace URLs
        run: |
          files=("android/app/src/main/AndroidManifest.xml"
                  "ios/Runner/Runner.entitlements"
                  "lib/bloc/notification/fcm_setting.dart"
                  "lib/bloc/notification/local_notification_setting.dart"
                  "lib/controller/webview_controller.dart"
                  "lib/screen/webview_screen.dart")

          for file in "${files[@]}"; do
            sed -i 's|www.dev.uspray.kr|www.uspray.kr|g' "$file"
          done

      - name: Commit and Push Changes
        run: |
          git config --global user.email ${{ secrets.GIT_USER_EMAIL }}
          git config --global user.name ${{ secrets.GIT_USER_NAME }}
          git add .
          git commit -m "URL changed: dev.uspray -> uspray"
          git push
